"""add priority and due date to tasks

Revision ID: 4d70ca637472
Revises: a017e3ebbc32
Create Date: 2026-08-28 14:01:07.578402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d70ca637472'
down_revision: Union[str, Sequence[str], None] = 'a017e3ebbc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    priority_enum = sa.Enum(
        "LOW",
        "MEDIUM",
        "HIGH",
        "URGENT",
        name="priority"
    )

    # Create PostgreSQL ENUM type first
    priority_enum.create(op.get_bind(), checkfirst=True)

    # Add priority column
    op.add_column(
        "Tasks",
        sa.Column(
            "priority",
            priority_enum,
            server_default="MEDIUM",
            nullable=False
        )
    )

    # Add optional due date
    op.add_column(
        "Tasks",
        sa.Column(
            "due_date",
            sa.DateTime(),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'due_date')
    op.drop_column('Tasks', 'priority')
    # ### end Alembic commands ###
