"""add estimated duration to tasks

Revision ID: d51c68e0b5dd
Revises: b0bb72957dd5
Create Date: 2026-10-03 10:16:58.808579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51c68e0b5dd'
down_revision: Union[str, Sequence[str], None] = 'b0bb72957dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_subtasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('group_task_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_task_id'], ['group_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Subtasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('Subtasks', sa.Column('task_id', sa.BigInteger(), nullable=True))
    op.alter_column('Subtasks', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('Subtasks_tasks_id_fkey'), 'Subtasks', type_='foreignkey')
    op.create_foreign_key(None, 'Subtasks', 'Tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Subtasks', 'tasks_id')
    op.add_column('Tasks', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('group_tasks', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_tasks', 'estimated_duration')
    op.drop_column('Tasks', 'estimated_duration')
    op.add_column('Subtasks', sa.Column('tasks_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Subtasks', type_='foreignkey')
    op.create_foreign_key(op.f('Subtasks_tasks_id_fkey'), 'Subtasks', 'Tasks', ['tasks_id'], ['id'], ondelete='CASCADE')
    op.alter_column('Subtasks', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Subtasks', 'task_id')
    op.drop_column('Subtasks', 'due_date')
    op.drop_table('group_subtasks')
    # ### end Alembic commands ###
